name: Generate Snake Animation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        run: |
          # Your commands to generate the animation
          echo "Snake animation generated."

      - name: Push changes to output branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b output
          git add .
          git commit -m "Generated snake animation"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/minh-nguyennhat/minh-nguyennhat.git output

        - name: Push changes to output branch
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git checkout -b output
            git add .
            if [ -n "$(git status --porcelain)" ]; then
              git commit -m "Generated snake animation"
              git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/minh-nguyennhat/minh-nguyennhat.git output
            else
              echo "No changes to commit"
            fi
